language: php

php:
  - '5.4'
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'
  - hhvm
  - nightly
  - hhvm
  - hhvm-nightly

before_script:
  - composer self-update
  - if [[ $(phpenv version-name) = "5.4" ]]; then composer require --dev phpunit/phpunit ^4; fi
  - if [[ $(phpenv version-name) = "5.6" ]]; then composer require --dev phpunit/phpunit ^5; fi
  - if [[ ${TRAVIS_PHP_VERSION:0:1} == "7" ]]; then composer require --dev phpunit/phpunit ^6; fi
  - composer install --no-interaction --prefer-dist --dev

script: 
  - protected/vendor/bin/phpunit --version